### Get all bookings
GET http://localhost:3000/api/bookings
Content-Type: application/json


### Get details of a specific booking
GET http://localhost:3000/api/bookings/:id
Content-Type: application/json


### Create a new booking(bike rental only)
POST http://localhost:3000/api/bookings
Content-Type: application/json

{
  "userId": "d7b7eae3-7435-4fc4-bb25-6b9c4d24ad14",
  "carId": "51610907-1e7e-437c-b400-c5cfeec4acd8",
  "startDate": "2024-12-01T10:00:00Z",
  "endDate": "2024-12-05T10:00:00Z",
  "totalAmount": 500
}



### Update booking status
PUT http://localhost:3000/api/bookings/:id/status
Content-Type: application/json

{
  "status": "canceled"
}



### Cancel a booking
PATCH http://localhost:3000/api/bookings/:id/cancel
Content-Type: application/json



### Manually Update Car Status
PATCH http://localhost:3000/api/bookings/car/:carId/status
Content-Type: application/json

{
  "status": "available"
}



