###Get All Available Cars
GET http://localhost:3000/api/cars
Content-Type: application/json



###Get Details of a Single Car
GET http://localhost:3000/api/cars/5be3780d-aeee-4552-a1c4-ea66f5d8c838
Content-Type: application/json


###Add a New Car
POST http://localhost:3000/api/cars
Content-Type: application/json


{
  "name": "TX",
  "brand": "Toyota",
  "registrationNumber": "1645",
  "pricePerDay": 100,
  "imageUrl": "https://example.com/toyota-corolla.jpg"
}



###Update Car Information
PUT http://localhost:3000/api/cars/f0bce6da-b348-409a-8ede-fa92b246f4b9
Content-Type: application/json

{
  "name": "TX",
  "brand": "Toyota",
  "registrationNumber": "1645",
  "pricePerDay": 120,  
  "status": "BOOKED",
  "imageUrl": "https://i.pinimg.com/736x/72/a9/18/72a9182b87ed72e13fec4e557de843fc.jpg"
}



###Soft Delete a Car
PUT http://localhost:3000/api/cars/a72c41b2-3dcf-4c45-ac02-7aabcfb1ee1d/soft-delete
Content-Type: application/json


###Delete a Car
DELETE http://localhost:3000/api/cars/8d9be9d8-9ccb-4e0f-961d-3c163b831175
Content-Type: application/json


### Manually Update Car Status
PATCH http://localhost:3000/api/bookings/car/61b32acd-6e62-4cae-9f05-d2b398ac92b4/status
Content-Type: application/json

{
  "status": "AVAILABLE"
}
