###Get All Available Cars
GET http://localhost:3000/api/cars
Content-Type: application/json



###Get Details of a Single Car
GET http://localhost:3000/api/cars/70a2ca4c-cd53-4f5f-abcb-f0f352f28ea4
Content-Type: application/json


###Add a New Car
POST http://localhost:3000/api/cars
Content-Type: application/json


{
  "name": "Toyota Corolla",
  "brand": "Toyota",
  "registrationNumber": "2023",
  "pricePerDay": 100,
  "imageUrl": "https://example.com/toyota-corolla.jpg"
}



###Update Car Information
PUT http://localhost:3000/api/cars/70a2ca4c-cd53-4f5f-abcb-f0f352f28ea4
Content-Type: application/json

{
  "name": "Toyota Camry",
  "brand": "Toyota",
  "registrationNumber": "2023",
  "pricePerDay": 120,  
  "status": "booked",
  "imageUrl": "https://example.com/toyota-camry.jpg"
}



###Soft Delete a Car
PUT http://localhost:3000/api/cars/70a2ca4c-cd53-4f5f-abcb-f0f352f28ea4/soft-delete
Content-Type: application/json


###Delete a Car
DELETE http://localhost:3000/api/cars/70a2ca4c-cd53-4f5f-abcb-f0f352f28ea4
Content-Type: application/json


