###Get All Available Cars
GET http://localhost:3000/api/cars
Content-Type: application/json



###Get Details of a Single Car
GET http://localhost:3000/api/cars/:id
Content-Type: application/json


###Add a New Car
POST http://localhost:3000/api/cars
Content-Type: application/json

{
  "name": "Toyota Corolla",
  "brand": "Toyota",
  "model": "2023",
  "status": "available",
  "pricePerDay": 100,
  "image": "https://example.com/toyota-corolla.jpg"
}


###Update Car Information
PUT http://localhost:3000/api/cars/:id
Content-Type: application/json

{
  "name": "Toyota Camry",
  "brand": "Toyota",
  "model": "2023",
  "status": "booked",
  "pricePerDay": 120,
  "image": "https://example.com/toyota-camry.jpg"
}



###Soft Delete a Car
PUT http://localhost:3000/api/cars/:id/soft-delete
Content-Type: application/json


###Delete a Car
DELETE http://localhost:3000/api/cars/:id
Content-Type: application/json


