###Get all available events
GET http://localhost:3000/api/events
Content-Type: application/json



###Get Details of a Single event
GET http://localhost:3000/api/events/393e60a7-9a6f-426c-9d06-d05642708e1d
Content-Type: application/json



###Add a New Event
POST http://localhost:3000/api/events
Content-Type: application/json

{
  "title": "COSPLAY EVENT 2024",
  "description": "An event on emerging cosplay.",
  "date": "2024-12-05T10:00:00Z",
  "location": "Tokyo, Japan",
  "imageUrl": "https://example.com/event-image.jpg",
  "organizerContact": "organizer@example.com"
}



###Update event Information
PUT http://localhost:3000/api/events/393e60a7-9a6f-426c-9d06-d05642708e1d
Content-Type: application/json

{
  "title": "Anime con Festival 2024",
  "description": "Updated details about the confest.",
  "imageUrl": "https://example.com/new-event-image.jpg"
}




###Delete an event
DELETE http://localhost:3000/api/events/13fd0761-388f-4d90-b8e0-f6b0b629e869
Content-Type: application/json
