###Get all available events
GET http://localhost:3000/api/events
Content-Type: application/json



###Get Details of a Single event
GET http://localhost:3000/api/events/51610907-1e7e-437c-b400-c5cfeec4acd8
Content-Type: application/json



###Add a New Event
POST http://localhost:3000/api/events
Content-Type: application/json

{
  "title": "Tech Conference 2024",
  "description": "A conference on emerging technologies.",
  "date": "2024-12-15",
  "location": "Silicon Valley, CA",
  "imageUrl": "https://example.com/event-image.jpg",
  "organizerContact": "organizer@example.com"
}



###Update event Information
PUT http://localhost:3000/api/events/d7b7eae3-7435-4fc4-bb25-6b9c4d24ad14
Content-Type: application/json

{
  "title": "Updated Tech Conference",
  "description": "Updated details about the conference.",
  "imageUrl": "https://example.com/new-event-image.jpg"
}




###Delete an event
DELETE http://localhost:3000/api/events/d7b7eae3-7435-4fc4-bb25-6b9c4d24ad14
Content-Type: application/json
