### Get all reviews 
GET http://localhost:3000/api/reviews
Content-Type: application/json



### Get a single review
GET http://localhost:3000/api/reviews/69254c81-00e6-42b9-a27f-b6200136435b
Content-Type: application/json



### Get Reviews by Car
GET http://localhost:3000/api/reviews/car/a72c41b2-3dcf-4c45-ac02-7aabcfb1ee1d
Content-Type: application/json



### Get Reviews by User
GET http://localhost:3000/api/reviews/user/bf5c75e5-2019-4b12-bc7c-bb7ebcf5f019
Content-Type: application/json



### Add a New Review
POST http://localhost:3000/api/reviews
Content-Type: application/json

{
  "userId": "bf5c75e5-2019-4b12-bc7c-bb7ebcf5f019",
  "carId": "a72c41b2-3dcf-4c45-ac02-7aabcfb1ee1d",
  "content": "The car was amazing! Smooth ride.",
  "rating": 5
}



### Update a review------------problem
PUT http://localhost:3000/api/reviews/23455b6f-bdc6-40dd-bc79-0da7f6fdfd68
Content-Type: application/json

{
  "rating": 4,
  "comment": "Great event but could improve."
}


### Delete a review
DELETE http://localhost:3000/api/reviews/23455b6f-bdc6-40dd-bc79-0da7f6fdfd68
Content-Type: application/json
