### Get all reviews 
GET http://localhost:3000/api/reviews
Content-Type: application/json



### Get a single review
GET http://localhost:3000/api/reviews/3c62d98f-cabf-4c2b-9d0f-7c1b32c5de2c
Content-Type: application/json



### Get Reviews by Car
GET http://localhost:3000/api/reviews/car/70a2ca4c-cd53-4f5f-abcb-f0f352f28ea4
Content-Type: application/json



### Get Reviews by User
GET http://localhost:3000/api/reviews/user/30e4ef59-0799-4051-85e2-6e9044752c4e
Content-Type: application/json



### Add a New Review
POST http://localhost:3000/api/reviews
Content-Type: application/json

{
  "userId": "30e4ef59-0799-4051-85e2-6e9044752c4e",
  "carId": "70a2ca4c-cd53-4f5f-abcb-f0f352f28ea4",
  "content": "The car was amazing! Smooth ride.",
  "rating": 5
}



# ### Update a review
# PUT http://localhost:3000/api/reviews/166a432e-8c08-4410-a7fa-92087002e234
# Content-Type: application/json

# {
#   "rating": 4,
#   "comment": "Great event but could improve."
# }


### Delete a review
DELETE http://localhost:3000/api/reviews/3c62d98f-cabf-4c2b-9d0f-7c1b32c5de2c
Content-Type: application/json
