### Get ticket details by booking ID
GET http://localhost:3000/api/tickets/booking/3e18ecd7-1cac-4339-b05e-1eefebddc197
Content-Type: application/json


### Get Tickets by User ID ************problem
GET http://localhost:3000/api/tickets/user/d2a6c9a3-d59d-4321-a7c9-8f9d52b9f76c
Content-Type: application/json



### Get all tickets 
GET http://localhost:3000/api/tickets
Content-Type: application/json



