### Register new user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "marvo Doe",
  "email": "marvo@example.com",
  "phone": "1234567890",
  "password": "onepiece"
}


### Login user
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "marvo@example.com",
  "password": "onepiece"
}



### Get all users
GET http://localhost:3000/api/users
Content-Type: application/json




### Get user profile
GET http://localhost:3000/api/users/d2a6c9a3-d59d-4321-a7c9-8f9d52b9f76c/profile
Content-Type: application/json



### Update user profile
PUT http://localhost:3000/api/users/bf5c75e5-2019-4b12-bc7c-bb7ebcf5f019/profile
Content-Type: application/json

{
  "name": "John Smith",
  "email": "johnsmith@example.com",
  "phone": "+9999943210"
}



### Get all user bookings 
GET http://localhost:3000/api/users/d2a6c9a3-d59d-4321-a7c9-8f9d52b9f76c/bookings
Content-Type: application/json



### Get all user reviews
GET http://localhost:3000/api/users/bf5c75e5-2019-4b12-bc7c-bb7ebcf5f019/reviews
Content-Type: application/json



### Delete user account---------PROBLEM
DELETE http://localhost:3000/api/users/bf5c75e5-2019-4b12-bc7c-bb7ebcf5f019


### Assign User Role
PUT http://localhost:3000/api/users/assign-role
Content-Type: application/json

{
  "userId": "45503a93-e10c-4d11-816e-6b4279c32e05",
  "role": "ORGANIZER"
}






# ### Deactivate user account
# PATCH http://localhost:3000/api/users/30e4ef59-0799-4051-85e2-6e9044752c4e/deactivate
# Content-Type: application/json


# ### Send reset password code (via email)
# POST http://localhost:3000/users/reset-password/code
# Content-Type: application/json

# {
#   "email": "janedoe@example.com"
# }


# ### Reset password
# POST http://localhost:3000/users/reset-password
# Content-Type: application/json

# {
#   "email": "janedoe@example.com",
#   "resetCode": "123456",
#   "newPassword": "newsecurepassword"
# }
