### Register new user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "phone": "+1234567890",
  "password": "securepassword"
}


### Login user
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "securepassword"
}



### Get user profile
GET http://localhost:3000/api/users/d7b7eae3-7435-4fc4-bb25-6b9c4d24ad14/profile
Content-Type: application/json



### Update user profile
PUT http://localhost:3000/api/users/d7b7eae3-7435-4fc4-bb25-6b9c4d24ad14/profile
Content-Type: application/json

{
  "name": "John Smith",
  "email": "johnsmith@example.com",
  "phone": "+9876543210"
}



### Get all user bookings (events and bikes)
GET http://localhost:3000/api/users/d7b7eae3-7435-4fc4-bb25-6b9c4d24ad14/bookings
Content-Type: application/json



### Get all user reviews
GET http://localhost:3000/api/users/d7b7eae3-7435-4fc4-bb25-6b9c4d24ad14/reviews
Content-Type: application/json


### Deactivate user account
PATCH http://localhost:3000/api/users/d7b7eae3-7435-4fc4-bb25-6b9c4d24ad14/deactivate
Content-Type: application/json



### Delete user account
DELETE http://localhost:3000/api/users/d7b7eae3-7435-4fc4-bb25-6b9c4d24ad14
Content-Type: application/json



### Assign User Role
PUT http://localhost:3000/api/users/assign-role
Content-Type: application/json

{
  "userId": "d7b7eae3-7435-4fc4-bb25-6b9c4d24ad14",
  "role": "admin"
}






# ### Send reset password code (via email)
# POST http://localhost:3000/users/reset-password/code
# Content-Type: application/json

# {
#   "email": "janedoe@example.com"
# }


# ### Reset password
# POST http://localhost:3000/users/reset-password
# Content-Type: application/json

# {
#   "email": "janedoe@example.com",
#   "resetCode": "123456",
#   "newPassword": "newsecurepassword"
# }

